import { ResizeSettings } from "./types";

export interface ProgrammaticPage {
  slug: string;
  title: string;
  metaDescription: string;
  h1: string;
  description: string;
  settings: Partial<ResizeSettings>;
  category: string;
  relatedPages?: string[];
}

// Social Media Platforms
const socialMediaPages: ProgrammaticPage[] = [
  // Instagram
  {
    slug: "resize-image-for-instagram-post",
    title: "Resize Images for Instagram Posts | Free Instagram Image Resizer",
    metaDescription: "Resize your images to the perfect Instagram post size (1080x1080px). Free, fast, and secure image resizer for Instagram.",
    h1: "Resize Images for Instagram Posts",
    description: "Instagram posts look best at 1080x1080 pixels (square format). Our tool automatically resizes your images to the perfect Instagram post dimensions while maintaining quality. All processing happens in your browser - your images never leave your device.",
    settings: {
      width: 1080,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-instagram-story", "resize-image-for-instagram-reel"],
  },
  {
    slug: "resize-image-for-instagram-story",
    title: "Resize Images for Instagram Stories | 1080x1920 Instagram Story Size",
    metaDescription: "Resize images to perfect Instagram Story dimensions (1080x1920px). Free tool optimized for Instagram vertical format.",
    h1: "Resize Images for Instagram Stories",
    description: "Instagram Stories require a 9:16 aspect ratio at 1080x1920 pixels. Upload your images and we'll resize them to the perfect Instagram Story dimensions. Your images stay private - everything processes locally in your browser.",
    settings: {
      width: 1080,
      height: 1920,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-instagram-post", "resize-image-for-instagram-reel"],
  },
  {
    slug: "resize-image-for-instagram-reel",
    title: "Resize Images for Instagram Reels | 1080x1920 Reel Cover Size",
    metaDescription: "Resize images for Instagram Reels covers (1080x1920px). Perfect dimensions for engaging Reel thumbnails.",
    h1: "Resize Images for Instagram Reels",
    description: "Instagram Reels covers use the same 9:16 vertical format as Stories - 1080x1920 pixels. Create eye-catching Reel covers with perfectly sized images. Fast, free, and completely private.",
    settings: {
      width: 1080,
      height: 1920,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-instagram-story", "resize-image-for-instagram-post"],
  },
  
  // Facebook
  {
    slug: "resize-image-for-facebook-post",
    title: "Resize Images for Facebook Posts | 1200x630 Facebook Image Size",
    metaDescription: "Resize images to optimal Facebook post size (1200x630px). Perfect for link previews and shared posts.",
    h1: "Resize Images for Facebook Posts",
    description: "Facebook posts display best at 1200x630 pixels, especially for link previews. This size ensures your images look great when shared. All processing happens securely in your browser.",
    settings: {
      width: 1200,
      height: 630,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-facebook-cover", "resize-image-for-facebook-profile"],
  },
  {
    slug: "resize-image-for-facebook-cover",
    title: "Resize Facebook Cover Photo | 820x312 Cover Image Size",
    metaDescription: "Resize your Facebook cover photo to the perfect size (820x312px). Free cover photo resizer for Facebook.",
    h1: "Resize Facebook Cover Photos",
    description: "Facebook cover photos display at 820x312 pixels on desktop. Upload your image and resize it to fit perfectly as your Facebook page or profile cover photo.",
    settings: {
      width: 820,
      height: 312,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-facebook-post", "resize-image-for-facebook-profile"],
  },
  {
    slug: "resize-image-for-facebook-profile",
    title: "Resize Facebook Profile Picture | 180x180 Profile Photo Size",
    metaDescription: "Resize your profile picture for Facebook (180x180px). Perfect square profile photo resizer.",
    h1: "Resize Facebook Profile Pictures",
    description: "Facebook profile pictures display at 180x180 pixels. Create a perfectly sized square profile photo for your Facebook account.",
    settings: {
      width: 180,
      height: 180,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-facebook-cover", "resize-image-for-facebook-post"],
  },

  // Twitter/X
  {
    slug: "resize-image-for-twitter-post",
    title: "Resize Images for Twitter/X Posts | 1200x675 Twitter Image Size",
    metaDescription: "Resize images to optimal Twitter post size (1200x675px). Perfect dimensions for tweets with images.",
    h1: "Resize Images for Twitter Posts",
    description: "Twitter displays images best at 1200x675 pixels (16:9 aspect ratio). Resize your images to look great in tweets and ensure maximum engagement.",
    settings: {
      width: 1200,
      height: 675,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-twitter-header", "resize-image-for-twitter-profile"],
  },
  {
    slug: "resize-image-for-twitter-header",
    title: "Resize Twitter Header Image | 1500x500 Twitter Banner Size",
    metaDescription: "Resize your Twitter header banner to perfect size (1500x500px). Free Twitter header image resizer.",
    h1: "Resize Twitter Header Images",
    description: "Twitter header images display at 1500x500 pixels. Create a professional-looking Twitter banner with the perfect dimensions.",
    settings: {
      width: 1500,
      height: 500,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-twitter-post", "resize-image-for-twitter-profile"],
  },
  {
    slug: "resize-image-for-twitter-profile",
    title: "Resize Twitter Profile Picture | 400x400 Profile Photo Size",
    metaDescription: "Resize profile pictures for Twitter (400x400px). Perfect square profile photo dimensions.",
    h1: "Resize Twitter Profile Pictures",
    description: "Twitter profile pictures display at 400x400 pixels. Create a crisp, square profile photo for your Twitter account.",
    settings: {
      width: 400,
      height: 400,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-twitter-header", "resize-image-for-twitter-post"],
  },

  // LinkedIn
  {
    slug: "resize-image-for-linkedin-post",
    title: "Resize Images for LinkedIn Posts | 1200x627 LinkedIn Image Size",
    metaDescription: "Resize images for LinkedIn posts (1200x627px). Optimal dimensions for professional LinkedIn content.",
    h1: "Resize Images for LinkedIn Posts",
    description: "LinkedIn posts display images best at 1200x627 pixels. Ensure your professional content looks sharp with properly sized images.",
    settings: {
      width: 1200,
      height: 627,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-linkedin-banner", "resize-image-for-linkedin-profile"],
  },
  {
    slug: "resize-image-for-linkedin-banner",
    title: "Resize LinkedIn Banner | 1584x396 LinkedIn Cover Photo Size",
    metaDescription: "Resize your LinkedIn banner to perfect size (1584x396px). Professional LinkedIn cover photo resizer.",
    h1: "Resize LinkedIn Banner Images",
    description: "LinkedIn banners display at 1584x396 pixels. Create a professional profile with a perfectly sized LinkedIn cover photo.",
    settings: {
      width: 1584,
      height: 396,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-linkedin-post", "resize-image-for-linkedin-profile"],
  },
  {
    slug: "resize-image-for-linkedin-profile",
    title: "Resize LinkedIn Profile Picture | 400x400 Profile Photo Size",
    metaDescription: "Resize profile pictures for LinkedIn (400x400px). Professional square profile photo dimensions.",
    h1: "Resize LinkedIn Profile Pictures",
    description: "LinkedIn profile pictures display at 400x400 pixels. Create a professional square profile photo for your LinkedIn account.",
    settings: {
      width: 400,
      height: 400,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-linkedin-banner", "resize-image-for-linkedin-post"],
  },

  // YouTube
  {
    slug: "resize-image-for-youtube-thumbnail",
    title: "Resize YouTube Thumbnail | 1280x720 Thumbnail Size",
    metaDescription: "Resize images for YouTube thumbnails (1280x720px). Perfect HD thumbnail dimensions for maximum engagement.",
    h1: "Resize YouTube Thumbnails",
    description: "YouTube thumbnails display at 1280x720 pixels (16:9 HD format). Create eye-catching thumbnails that drive clicks with perfectly sized images.",
    settings: {
      width: 1280,
      height: 720,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-youtube-banner", "resize-to-1280x720"],
  },
  {
    slug: "resize-image-for-youtube-banner",
    title: "Resize YouTube Banner | 2560x1440 Channel Art Size",
    metaDescription: "Resize YouTube channel banner to perfect size (2560x1440px). Professional YouTube channel art resizer.",
    h1: "Resize YouTube Channel Banners",
    description: "YouTube channel art displays at 2560x1440 pixels for optimal viewing across devices. Create professional channel branding with correctly sized banners.",
    settings: {
      width: 2560,
      height: 1440,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-youtube-thumbnail", "resize-to-2560x1440"],
  },

  // TikTok
  {
    slug: "resize-image-for-tiktok",
    title: "Resize Images for TikTok | 1080x1920 TikTok Cover Size",
    metaDescription: "Resize images for TikTok covers (1080x1920px). Perfect vertical format for TikTok video thumbnails.",
    h1: "Resize Images for TikTok",
    description: "TikTok uses a 9:16 vertical format at 1080x1920 pixels. Create engaging video covers and profile content with properly sized images.",
    settings: {
      width: 1080,
      height: 1920,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-instagram-story", "resize-image-for-instagram-reel"],
  },

  // Pinterest
  {
    slug: "resize-image-for-pinterest",
    title: "Resize Images for Pinterest | 1000x1500 Pin Size",
    metaDescription: "Resize images for Pinterest pins (1000x1500px). Optimal 2:3 aspect ratio for maximum engagement.",
    h1: "Resize Images for Pinterest",
    description: "Pinterest pins perform best at 1000x1500 pixels (2:3 aspect ratio). Resize your images to create pins that stand out and drive traffic.",
    settings: {
      width: 1000,
      height: 1500,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-to-1000x1500", "compress-image-for-web"],
  },

  // Snapchat
  {
    slug: "resize-image-for-snapchat",
    title: "Resize Images for Snapchat | 1080x1920 Snap Size",
    metaDescription: "Resize images for Snapchat (1080x1920px). Perfect vertical format for Snapchat stories and snaps.",
    h1: "Resize Images for Snapchat",
    description: "Snapchat uses a 9:16 vertical format at 1080x1920 pixels. Resize your images to fit perfectly in Snapchat stories and snaps.",
    settings: {
      width: 1080,
      height: 1920,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-instagram-story", "resize-image-for-tiktok"],
  },

  // WhatsApp
  {
    slug: "resize-image-for-whatsapp",
    title: "Resize Images for WhatsApp | Compress Images for Messaging",
    metaDescription: "Resize and compress images for WhatsApp. Reduce file size while maintaining quality for faster messaging.",
    h1: "Resize Images for WhatsApp",
    description: "WhatsApp automatically compresses images, but you can optimize them first for better quality. Resize to 1600px width and reduce file size for faster sending.",
    settings: {
      width: 1600,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "social-media",
    relatedPages: ["compress-image-for-email", "resize-image-for-web"],
  },
];

// Use Case Pages
const useCasePages: ProgrammaticPage[] = [
  {
    slug: "resize-image-for-email",
    title: "Resize Images for Email | Reduce Email Attachment Size",
    metaDescription: "Resize images for email attachments. Reduce file size to stay under email limits while maintaining quality.",
    h1: "Resize Images for Email Attachments",
    description: "Email providers limit attachment sizes (typically 25MB). Resize your images to 800-1600px wide and reduce quality slightly to create smaller files that send faster and look great.",
    settings: {
      width: 800,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "use-case",
    relatedPages: ["compress-image-for-email", "resize-image-for-web"],
  },
  {
    slug: "compress-image-for-email",
    title: "Compress Images for Email | Reduce Image File Size",
    metaDescription: "Compress images for email to reduce file size. Stay under attachment limits with optimized images.",
    h1: "Compress Images for Email",
    description: "Reduce image file sizes for email without losing noticeable quality. Our tool compresses images to around 70-75% quality, perfect for email attachments.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 70,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-email", "compress-image-for-web"],
  },
  {
    slug: "resize-image-for-web",
    title: "Resize Images for Web | Optimize Images for Websites",
    metaDescription: "Resize and optimize images for web. Reduce file size for faster page loading and better SEO.",
    h1: "Resize Images for Web",
    description: "Web images should be optimized for fast loading. Resize to appropriate dimensions (typically 1920px max) and compress to 80% quality for the perfect balance of quality and performance.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "use-case",
    relatedPages: ["compress-image-for-web", "convert-to-webp"],
  },
  {
    slug: "compress-image-for-web",
    title: "Compress Images for Web | Website Image Optimization",
    metaDescription: "Compress images for websites. Improve page speed and SEO with optimized images.",
    h1: "Compress Images for Web",
    description: "Fast-loading websites rank better on Google. Compress your images to reduce file size by 50-70% while maintaining visual quality. Perfect for website optimization.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-web", "convert-to-webp"],
  },
  {
    slug: "resize-profile-picture",
    title: "Resize Profile Picture | Create Square Profile Photos",
    metaDescription: "Resize profile pictures to square format. Perfect for social media profile photos and avatars.",
    h1: "Resize Profile Pictures",
    description: "Most social media platforms use square profile pictures. Resize your photos to 400x400 or 500x500 pixels for crisp, professional-looking profile images.",
    settings: {
      width: 400,
      height: 400,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-instagram-post", "resize-image-for-facebook-profile"],
  },
  {
    slug: "resize-thumbnail",
    title: "Resize Thumbnail | Create Small Preview Images",
    metaDescription: "Resize images to create thumbnails. Perfect small preview images for galleries and listings.",
    h1: "Resize Images to Thumbnails",
    description: "Thumbnails are small preview images, typically 150-300 pixels. Create fast-loading thumbnail images for photo galleries, product listings, and more.",
    settings: {
      width: 300,
      height: 300,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "use-case",
    relatedPages: ["resize-profile-picture", "compress-image-for-web"],
  },
  {
    slug: "resize-image-for-print",
    title: "Resize Images for Print | High Resolution Print Images",
    metaDescription: "Resize images for printing. Maintain high resolution at 300 DPI for quality prints.",
    h1: "Resize Images for Print",
    description: "Print images need higher resolution than web images. Keep larger dimensions (2400-3600px) and use 90-100% quality for professional-quality prints.",
    settings: {
      width: 3000,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  {
    slug: "resize-product-image",
    title: "Resize Product Images | E-commerce Image Optimization",
    metaDescription: "Resize product images for online stores. Optimize for fast loading while maintaining detail.",
    h1: "Resize Product Images",
    description: "E-commerce product images should be 1000-2000 pixels to show detail while loading fast. Resize and optimize your product photos for better conversions.",
    settings: {
      width: 1500,
      height: 1500,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  {
    slug: "resize-blog-image",
    title: "Resize Blog Images | Featured Image Optimization",
    metaDescription: "Resize blog featured images and article photos. Optimize for fast loading and SEO.",
    h1: "Resize Blog Images",
    description: "Blog images should be 1200-1920px wide for featured images. Resize and compress for fast page loading and better search rankings.",
    settings: {
      width: 1200,
      height: 630,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  {
    slug: "resize-website-header",
    title: "Resize Website Header Image | Hero Image Optimization",
    metaDescription: "Resize header images for websites. Perfect hero image dimensions for desktop and mobile.",
    h1: "Resize Website Header Images",
    description: "Website header images (hero images) work best at 1920x1080 pixels. Resize to full HD dimensions for crisp display on all screen sizes.",
    settings: {
      width: 1920,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-web", "resize-to-1920x1080"],
  },
  {
    slug: "batch-resize-images",
    title: "Batch Resize Images | Resize Multiple Images at Once",
    metaDescription: "Batch resize multiple images at once. Free bulk image resizer with ZIP download.",
    h1: "Batch Resize Multiple Images",
    description: "Upload multiple images and resize them all with the same settings. Perfect for resizing photo albums, product catalogs, or bulk image processing. Download all as a convenient ZIP file.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  {
    slug: "resize-image-percentage",
    title: "Resize Image by Percentage | Scale Images Proportionally",
    metaDescription: "Resize images by percentage. Scale images to 50%, 25%, or any percentage while maintaining aspect ratio.",
    h1: "Resize Images by Percentage",
    description: "Scale images proportionally by percentage. Reduce to 50% for half size, 25% for quarter size, or any custom percentage. Aspect ratio is automatically maintained.",
    settings: {
      width: 0,
      height: 0,
      usePercentage: true,
      percentage: 50,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-web", "batch-resize-images"],
  },
  {
    slug: "resize-screenshot",
    title: "Resize Screenshot | Optimize Screen Capture Images",
    metaDescription: "Resize screenshots for sharing. Reduce file size while keeping text readable.",
    h1: "Resize Screenshots",
    description: "Screenshots are often too large. Resize to 1920px max width and use PNG format to keep text sharp, or use JPG at 85% quality for smaller file sizes.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/png",
      quality: 85,
    },
    category: "use-case",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  {
    slug: "resize-logo",
    title: "Resize Logo | Scale Logo Images",
    metaDescription: "Resize logo images for different uses. Maintain transparency and quality.",
    h1: "Resize Logo Images",
    description: "Resize logos for websites, social media, or print. Use PNG format to preserve transparency and maintain crisp edges at any size.",
    settings: {
      width: 500,
      height: 0,
      outputFormat: "image/png",
      quality: 100,
    },
    category: "use-case",
    relatedPages: ["convert-to-png", "resize-profile-picture"],
  },
  {
    slug: "resize-avatar",
    title: "Resize Avatar | Create Small Profile Icons",
    metaDescription: "Resize avatars and profile icons. Perfect small sizes for forums and websites.",
    h1: "Resize Avatar Images",
    description: "Avatars are small profile images, typically 64x64 to 128x128 pixels. Create perfectly sized square avatars for forums, comment sections, and user profiles.",
    settings: {
      width: 128,
      height: 128,
      outputFormat: "image/png",
      quality: 90,
    },
    category: "use-case",
    relatedPages: ["resize-profile-picture", "resize-thumbnail"],
  },
];

// Format Conversion Pages
const formatConversionPages: ProgrammaticPage[] = [
  {
    slug: "convert-png-to-jpg",
    title: "Convert PNG to JPG | Free PNG to JPEG Converter",
    metaDescription: "Convert PNG images to JPG format online. Free, fast, and secure PNG to JPEG conversion.",
    h1: "Convert PNG to JPG",
    description: "Convert PNG files to JPG format to reduce file size. JPG files are typically 50-80% smaller than PNG, perfect for photos and web images. All conversion happens in your browser.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "format-conversion",
    relatedPages: ["convert-jpg-to-png", "convert-to-webp"],
  },
  {
    slug: "convert-jpg-to-png",
    title: "Convert JPG to PNG | Free JPEG to PNG Converter",
    metaDescription: "Convert JPG images to PNG format. Free online JPEG to PNG converter with transparency support.",
    h1: "Convert JPG to PNG",
    description: "Convert JPG files to PNG format for lossless quality and transparency support. PNG is ideal for graphics, logos, and images with text.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/png",
      quality: 100,
    },
    category: "format-conversion",
    relatedPages: ["convert-png-to-jpg", "convert-to-webp"],
  },
  {
    slug: "convert-to-webp",
    title: "Convert Images to WebP | Free WebP Converter",
    metaDescription: "Convert images to WebP format for smaller file sizes. Free online WebP converter.",
    h1: "Convert Images to WebP",
    description: "WebP images are 25-35% smaller than JPG at similar quality. Convert your images to WebP for faster website loading and better performance.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/webp",
      quality: 85,
    },
    category: "format-conversion",
    relatedPages: ["convert-png-to-jpg", "compress-image-for-web"],
  },
  {
    slug: "convert-webp-to-jpg",
    title: "Convert WebP to JPG | Free WebP to JPEG Converter",
    metaDescription: "Convert WebP images to JPG format. Free online WebP to JPEG conversion.",
    h1: "Convert WebP to JPG",
    description: "Convert WebP files to JPG for broader compatibility. JPG works everywhere, making it perfect for sharing and printing.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "format-conversion",
    relatedPages: ["convert-to-webp", "convert-png-to-jpg"],
  },
  {
    slug: "convert-webp-to-png",
    title: "Convert WebP to PNG | Free WebP to PNG Converter",
    metaDescription: "Convert WebP images to PNG format. Preserve quality with lossless PNG conversion.",
    h1: "Convert WebP to PNG",
    description: "Convert WebP files to PNG for lossless quality and transparency support. Perfect when you need the highest quality output.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/png",
      quality: 100,
    },
    category: "format-conversion",
    relatedPages: ["convert-to-webp", "convert-jpg-to-png"],
  },
  {
    slug: "convert-gif-to-jpg",
    title: "Convert GIF to JPG | Free GIF to JPEG Converter",
    metaDescription: "Convert GIF images to JPG format. Reduce file size while maintaining quality.",
    h1: "Convert GIF to JPG",
    description: "Convert static GIF images to JPG format for smaller file sizes and better photo quality. Note: Animation will be lost.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "format-conversion",
    relatedPages: ["convert-png-to-jpg", "convert-to-webp"],
  },
  {
    slug: "convert-gif-to-png",
    title: "Convert GIF to PNG | Free GIF to PNG Converter",
    metaDescription: "Convert GIF images to PNG format. Lossless conversion for better quality.",
    h1: "Convert GIF to PNG",
    description: "Convert GIF files to PNG for better quality and transparency support. Perfect for logos and graphics originally saved as GIF.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/png",
      quality: 100,
    },
    category: "format-conversion",
    relatedPages: ["convert-jpg-to-png", "convert-gif-to-jpg"],
  },
  {
    slug: "convert-to-png",
    title: "Convert Images to PNG | Free PNG Converter",
    metaDescription: "Convert any image to PNG format. Lossless quality with transparency support.",
    h1: "Convert Images to PNG",
    description: "Convert JPG, WebP, GIF, and other formats to PNG. PNG offers lossless compression and transparency support, perfect for logos and graphics.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/png",
      quality: 100,
    },
    category: "format-conversion",
    relatedPages: ["convert-to-webp", "convert-png-to-jpg"],
  },
  {
    slug: "convert-to-jpg",
    title: "Convert Images to JPG | Free JPEG Converter",
    metaDescription: "Convert any image to JPG format. Universal format with great compression.",
    h1: "Convert Images to JPG",
    description: "Convert PNG, WebP, GIF, and other formats to JPG. JPEG offers excellent compression for photos and works everywhere.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "format-conversion",
    relatedPages: ["convert-to-webp", "convert-to-png"],
  },
  {
    slug: "convert-png-to-webp",
    title: "Convert PNG to WebP | Reduce PNG File Size",
    metaDescription: "Convert PNG to WebP for smaller file sizes. Free PNG to WebP converter.",
    h1: "Convert PNG to WebP",
    description: "Convert PNG files to WebP format and reduce file size by 25-35% while maintaining quality. Perfect for website optimization.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/webp",
      quality: 90,
    },
    category: "format-conversion",
    relatedPages: ["convert-to-webp", "convert-png-to-jpg"],
  },
  {
    slug: "convert-jpg-to-webp",
    title: "Convert JPG to WebP | Reduce JPEG File Size",
    metaDescription: "Convert JPG to WebP for even smaller files. Free JPEG to WebP converter.",
    h1: "Convert JPG to WebP",
    description: "Convert JPG files to WebP format and reduce file size by 25-35% compared to JPEG. Faster website loading with modern image format.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/webp",
      quality: 85,
    },
    category: "format-conversion",
    relatedPages: ["convert-to-webp", "convert-png-to-webp"],
  },
];

// Common Dimension Pages
const dimensionPages: ProgrammaticPage[] = [
  {
    slug: "resize-to-1920x1080",
    title: "Resize to 1920x1080 | Full HD Image Resizer",
    metaDescription: "Resize images to 1920x1080 pixels (Full HD). Perfect for HD displays and presentations.",
    h1: "Resize Images to 1920x1080 (Full HD)",
    description: "1920x1080 is the standard Full HD resolution, perfect for desktop wallpapers, presentations, and HD displays. Resize your images to Full HD dimensions.",
    settings: {
      width: 1920,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-to-1280x720", "resize-to-3840x2160"],
  },
  {
    slug: "resize-to-1280x720",
    title: "Resize to 1280x720 | HD Ready Image Resizer",
    metaDescription: "Resize images to 1280x720 pixels (HD 720p). Standard HD dimensions for videos and displays.",
    h1: "Resize Images to 1280x720 (HD 720p)",
    description: "1280x720 is HD 720p resolution, widely used for HD video thumbnails, YouTube thumbnails, and medium-resolution displays.",
    settings: {
      width: 1280,
      height: 720,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-to-1920x1080", "resize-image-for-youtube-thumbnail"],
  },
  {
    slug: "resize-to-1080x1080",
    title: "Resize to 1080x1080 | Square Image Resizer",
    metaDescription: "Resize images to 1080x1080 pixels. Perfect square format for Instagram and social media.",
    h1: "Resize Images to 1080x1080 (Square)",
    description: "1080x1080 is the perfect square format for Instagram posts, Facebook posts, and other square social media content.",
    settings: {
      width: 1080,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-image-for-instagram-post", "resize-to-800x800"],
  },
  {
    slug: "resize-to-800x600",
    title: "Resize to 800x600 | Standard 4:3 Image Resizer",
    metaDescription: "Resize images to 800x600 pixels. Classic 4:3 aspect ratio for emails and web.",
    h1: "Resize Images to 800x600",
    description: "800x600 is a classic resolution with 4:3 aspect ratio, perfect for email attachments and smaller web images.",
    settings: {
      width: 800,
      height: 600,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "dimensions",
    relatedPages: ["resize-image-for-email", "resize-to-1024x768"],
  },
  {
    slug: "resize-to-1024x768",
    title: "Resize to 1024x768 | 4:3 Image Resizer",
    metaDescription: "Resize images to 1024x768 pixels. Standard 4:3 resolution for presentations and web.",
    h1: "Resize Images to 1024x768",
    description: "1024x768 is a standard 4:3 resolution, commonly used for presentations, older displays, and web content.",
    settings: {
      width: 1024,
      height: 768,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-to-800x600", "resize-to-1920x1080"],
  },
  {
    slug: "resize-to-640x480",
    title: "Resize to 640x480 | Small 4:3 Image Resizer",
    metaDescription: "Resize images to 640x480 pixels. Compact 4:3 format for small displays and thumbnails.",
    h1: "Resize Images to 640x480",
    description: "640x480 is a compact 4:3 resolution, perfect for small displays, thumbnails, and reducing file size significantly.",
    settings: {
      width: 640,
      height: 480,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "dimensions",
    relatedPages: ["resize-to-800x600", "resize-thumbnail"],
  },
  {
    slug: "resize-to-2560x1440",
    title: "Resize to 2560x1440 | 2K QHD Image Resizer",
    metaDescription: "Resize images to 2560x1440 pixels (2K QHD). High resolution for modern displays.",
    h1: "Resize Images to 2560x1440 (2K QHD)",
    description: "2560x1440 is 2K QHD resolution, perfect for high-resolution displays, gaming monitors, and professional content.",
    settings: {
      width: 2560,
      height: 1440,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-to-1920x1080", "resize-to-3840x2160"],
  },
  {
    slug: "resize-to-3840x2160",
    title: "Resize to 3840x2160 | 4K UHD Image Resizer",
    metaDescription: "Resize images to 3840x2160 pixels (4K UHD). Ultra high definition resolution.",
    h1: "Resize Images to 3840x2160 (4K UHD)",
    description: "3840x2160 is 4K UHD resolution, the highest standard for consumer displays. Perfect for 4K screens and high-quality content.",
    settings: {
      width: 3840,
      height: 2160,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "dimensions",
    relatedPages: ["resize-to-2560x1440", "resize-to-1920x1080"],
  },
  {
    slug: "resize-to-500x500",
    title: "Resize to 500x500 | Medium Square Image Resizer",
    metaDescription: "Resize images to 500x500 pixels. Perfect medium square size for profiles and avatars.",
    h1: "Resize Images to 500x500 (Medium Square)",
    description: "500x500 is a medium square format, ideal for profile pictures, avatars, and small product images.",
    settings: {
      width: 500,
      height: 500,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-to-1080x1080", "resize-profile-picture"],
  },
  {
    slug: "resize-to-300x300",
    title: "Resize to 300x300 | Small Square Thumbnail Resizer",
    metaDescription: "Resize images to 300x300 pixels. Perfect small square thumbnail size.",
    h1: "Resize Images to 300x300 (Small Square)",
    description: "300x300 is a common thumbnail size, perfect for small product images, icons, and preview thumbnails.",
    settings: {
      width: 300,
      height: 300,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "dimensions",
    relatedPages: ["resize-thumbnail", "resize-to-500x500"],
  },
  {
    slug: "resize-to-800x800",
    title: "Resize to 800x800 | Square Product Image Resizer",
    metaDescription: "Resize images to 800x800 pixels. Perfect for product images and square content.",
    h1: "Resize Images to 800x800 (Square)",
    description: "800x800 is a popular e-commerce size, ideal for product images that show detail without huge file sizes.",
    settings: {
      width: 800,
      height: 800,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-product-image", "resize-to-1080x1080"],
  },
  {
    slug: "resize-to-1200x630",
    title: "Resize to 1200x630 | Social Media Share Image Resizer",
    metaDescription: "Resize to 1200x630 pixels. Perfect for Facebook, Twitter, and LinkedIn sharing.",
    h1: "Resize Images to 1200x630 (Social Share)",
    description: "1200x630 is the optimal size for social media sharing across Facebook, Twitter, and LinkedIn. Perfect for link previews and shared content.",
    settings: {
      width: 1200,
      height: 630,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-image-for-facebook-post", "resize-image-for-twitter-post"],
  },
  {
    slug: "resize-to-1080x1920",
    title: "Resize to 1080x1920 | Vertical 9:16 Image Resizer",
    metaDescription: "Resize to 1080x1920 pixels. Perfect vertical format for Stories and Reels.",
    h1: "Resize Images to 1080x1920 (Vertical)",
    description: "1080x1920 is the 9:16 vertical format used by Instagram Stories, TikTok, Snapchat, and Reels. Perfect for mobile-first content.",
    settings: {
      width: 1080,
      height: 1920,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-image-for-instagram-story", "resize-image-for-tiktok"],
  },
  {
    slug: "resize-to-1000x1500",
    title: "Resize to 1000x1500 | Pinterest Pin Image Resizer",
    metaDescription: "Resize to 1000x1500 pixels. Optimal 2:3 Pinterest pin dimensions.",
    h1: "Resize Images to 1000x1500 (Pinterest)",
    description: "1000x1500 is the perfect 2:3 ratio for Pinterest pins. This size maximizes engagement and visibility on Pinterest.",
    settings: {
      width: 1000,
      height: 1500,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-image-for-pinterest", "resize-to-1080x1920"],
  },
  {
    slug: "resize-to-1600x900",
    title: "Resize to 1600x900 | 16:9 Widescreen Image Resizer",
    metaDescription: "Resize to 1600x900 pixels. Standard 16:9 widescreen format.",
    h1: "Resize Images to 1600x900 (16:9 Widescreen)",
    description: "1600x900 is a 16:9 widescreen resolution, commonly used for medium-sized displays and web banners.",
    settings: {
      width: 1600,
      height: 900,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "dimensions",
    relatedPages: ["resize-to-1920x1080", "resize-to-1280x720"],
  },
];

// Combo pages (combining use case + format/dimension)
const comboPages: ProgrammaticPage[] = [
  {
    slug: "resize-instagram-post-1080x1080",
    title: "Resize to 1080x1080 for Instagram Posts | Instagram Square",
    metaDescription: "Resize images to perfect Instagram post size 1080x1080. One-click Instagram resizing.",
    h1: "Resize to 1080x1080 for Instagram Posts",
    description: "The perfect Instagram post size is 1080x1080 pixels. Upload your photo and we'll resize it to Instagram's optimal dimensions automatically.",
    settings: {
      width: 1080,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-for-instagram-post", "resize-to-1080x1080"],
  },
  {
    slug: "resize-instagram-story-1080x1920",
    title: "Resize to 1080x1920 for Instagram Stories | Story Size",
    metaDescription: "Resize images to Instagram Story size 1080x1920. Perfect vertical format.",
    h1: "Resize to 1080x1920 for Instagram Stories",
    description: "Instagram Stories require 1080x1920 pixels (9:16 ratio). Resize your images to fit perfectly in Instagram Stories format.",
    settings: {
      width: 1080,
      height: 1920,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-for-instagram-story", "resize-to-1080x1920"],
  },
  {
    slug: "resize-facebook-post-1200x630",
    title: "Resize to 1200x630 for Facebook Posts | Facebook Share Size",
    metaDescription: "Resize images to Facebook post size 1200x630. Perfect for link sharing.",
    h1: "Resize to 1200x630 for Facebook Posts",
    description: "Facebook displays shared images best at 1200x630 pixels. Resize your images for optimal Facebook post appearance.",
    settings: {
      width: 1200,
      height: 630,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-for-facebook-post", "resize-to-1200x630"],
  },
  {
    slug: "resize-youtube-thumbnail-1280x720",
    title: "Resize to 1280x720 for YouTube Thumbnails | HD Thumbnail",
    metaDescription: "Resize images to YouTube thumbnail size 1280x720. Perfect HD thumbnail dimensions.",
    h1: "Resize to 1280x720 for YouTube Thumbnails",
    description: "YouTube thumbnails display at 1280x720 pixels (HD 720p). Create perfect thumbnails that attract clicks.",
    settings: {
      width: 1280,
      height: 720,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "combo",
    relatedPages: ["resize-image-for-youtube-thumbnail", "resize-to-1280x720"],
  },
  {
    slug: "compress-jpg-for-email",
    title: "Compress JPG for Email | Reduce JPEG Email Attachment Size",
    metaDescription: "Compress JPG images for email. Reduce file size to fit email attachment limits.",
    h1: "Compress JPG Images for Email",
    description: "Reduce JPG file sizes for email attachments. Compress to 70-75% quality to create smaller files that send quickly while maintaining good quality.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 70,
    },
    category: "combo",
    relatedPages: ["resize-image-for-email", "compress-image-for-email"],
  },
  {
    slug: "compress-png-to-jpg",
    title: "Compress PNG to JPG | Convert and Reduce File Size",
    metaDescription: "Convert PNG to JPG and compress. Dramatically reduce file size for web and email.",
    h1: "Convert PNG to JPG and Compress",
    description: "Convert PNG to JPG format and compress to reduce file size by 50-80%. Perfect for making large PNG files email-friendly and web-optimized.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "combo",
    relatedPages: ["convert-png-to-jpg", "compress-image-for-email"],
  },
  {
    slug: "resize-and-convert-to-webp",
    title: "Resize and Convert to WebP | Optimize Images for Web",
    metaDescription: "Resize images and convert to WebP format. Maximum compression for fast websites.",
    h1: "Resize and Convert Images to WebP",
    description: "Resize your images to web-friendly dimensions (1920px max) and convert to WebP format for 25-35% smaller file sizes. Perfect for website optimization.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/webp",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["convert-to-webp", "resize-image-for-web"],
  },
  {
    slug: "resize-jpg-for-web",
    title: "Resize JPG for Web | Optimize JPEG Images for Websites",
    metaDescription: "Resize JPG images for web. Optimize JPEG photos for fast loading websites.",
    h1: "Resize JPG Images for Web",
    description: "Resize JPG photos to 1920px max width and compress to 80% quality for perfect web optimization. Fast loading, great quality.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  {
    slug: "resize-png-for-web",
    title: "Resize PNG for Web | Optimize PNG Images for Websites",
    metaDescription: "Resize PNG images for web while preserving transparency. Web-optimized PNG sizes.",
    h1: "Resize PNG Images for Web",
    description: "Resize PNG images to web-friendly dimensions while maintaining transparency and quality. Perfect for logos and graphics on websites.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/png",
      quality: 100,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "convert-png-to-jpg"],
  },
  {
    slug: "convert-and-resize-for-instagram",
    title: "Convert and Resize for Instagram | Optimize Images for IG",
    metaDescription: "Convert any image format and resize for Instagram. One-click Instagram optimization.",
    h1: "Convert and Resize Images for Instagram",
    description: "Upload any image format and we'll convert it to JPG and resize to perfect Instagram post dimensions (1080x1080). One-click Instagram prep.",
    settings: {
      width: 1080,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-for-instagram-post", "convert-to-jpg"],
  },
  // Adding more high-value combo pages
  {
    slug: "resize-profile-picture-400x400",
    title: "Resize Profile Picture to 400x400 | Social Media Profile Size",
    metaDescription: "Resize profile pictures to 400x400 pixels. Perfect for all social media platforms.",
    h1: "Resize Profile Pictures to 400x400",
    description: "400x400 pixels is the standard profile picture size for most social media platforms including Twitter, LinkedIn, and Facebook.",
    settings: {
      width: 400,
      height: 400,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "combo",
    relatedPages: ["resize-profile-picture", "resize-to-500x500"],
  },
  {
    slug: "compress-image-50-percent",
    title: "Compress Image by 50% | Reduce to Half Size",
    metaDescription: "Compress images to 50% of original size. Quick file size reduction.",
    h1: "Reduce Image Size by 50%",
    description: "Quickly reduce image file size by compressing to 50% quality. Perfect for reducing large image files while maintaining acceptable quality.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 50,
    },
    category: "combo",
    relatedPages: ["compress-image-for-email", "compress-image-for-web"],
  },
  {
    slug: "resize-hd-1920x1080",
    title: "Resize to HD 1920x1080 | Full HD Image Conversion",
    metaDescription: "Resize images to Full HD 1920x1080. Perfect for HD displays and presentations.",
    h1: "Resize Images to Full HD (1920x1080)",
    description: "Convert your images to Full HD resolution (1920x1080 pixels). Perfect for HD monitors, TVs, and presentations.",
    settings: {
      width: 1920,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-to-1920x1080", "resize-website-header"],
  },
  {
    slug: "resize-4k-3840x2160",
    title: "Resize to 4K 3840x2160 | Ultra HD Image Conversion",
    metaDescription: "Resize images to 4K UHD 3840x2160. Ultra high definition image sizing.",
    h1: "Resize Images to 4K (3840x2160)",
    description: "Convert your images to 4K Ultra HD resolution (3840x2160 pixels). Perfect for 4K displays and high-quality digital content.",
    settings: {
      width: 3840,
      height: 2160,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "combo",
    relatedPages: ["resize-to-3840x2160", "resize-to-2560x1440"],
  },
  {
    slug: "batch-convert-png-to-jpg",
    title: "Batch Convert PNG to JPG | Convert Multiple PNGs to JPEG",
    metaDescription: "Convert multiple PNG images to JPG at once. Batch PNG to JPEG conversion.",
    h1: "Batch Convert PNG to JPG",
    description: "Upload multiple PNG files and convert them all to JPG format in one go. Download all as a convenient ZIP file. Perfect for bulk photo processing.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["convert-png-to-jpg", "batch-resize-images"],
  },
  {
    slug: "batch-resize-for-web",
    title: "Batch Resize Images for Web | Bulk Web Image Optimizer",
    metaDescription: "Batch resize multiple images for web. Optimize all your images at once.",
    h1: "Batch Resize Images for Web",
    description: "Upload multiple images and resize them all to web-friendly dimensions (1920px max width) at once. Download as ZIP.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "combo",
    relatedPages: ["batch-resize-images", "resize-image-for-web"],
  },
  {
    slug: "thumbnail-generator",
    title: "Thumbnail Generator | Create Image Thumbnails",
    metaDescription: "Generate thumbnails from images. Create small preview images automatically.",
    h1: "Generate Image Thumbnails",
    description: "Automatically create 300x300 pixel thumbnails from your images. Perfect for galleries, product listings, and previews.",
    settings: {
      width: 300,
      height: 300,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "combo",
    relatedPages: ["resize-thumbnail", "resize-to-300x300"],
  },
  {
    slug: "square-image-maker",
    title: "Square Image Maker | Convert to Square Format",
    metaDescription: "Make square images for social media. Convert any image to square format.",
    h1: "Make Square Images",
    description: "Convert any image to square format (1080x1080). Perfect for Instagram, Facebook, and other social media platforms that prefer square images.",
    settings: {
      width: 1080,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-to-1080x1080", "resize-image-for-instagram-post"],
  },
  {
    slug: "optimize-image-for-seo",
    title: "Optimize Images for SEO | Reduce Size for Faster Loading",
    metaDescription: "Optimize images for SEO. Reduce file size for faster page loading and better rankings.",
    h1: "Optimize Images for SEO",
    description: "Optimize your images for search engines by resizing to 1920px max width and compressing to 75% quality. Faster loading = better SEO rankings.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  {
    slug: "mobile-friendly-image-resizer",
    title: "Mobile Friendly Image Resizer | Optimize for Mobile Devices",
    metaDescription: "Resize images for mobile devices. Create mobile-friendly images that load fast.",
    h1: "Resize Images for Mobile Devices",
    description: "Optimize images for mobile devices by resizing to 1200px max width and compressing. Faster loading on mobile networks.",
    settings: {
      width: 1200,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  // More high-traffic combo opportunities
  {
    slug: "compress-image-without-losing-quality",
    title: "Compress Image Without Losing Quality | Smart Compression",
    metaDescription: "Compress images while maintaining quality. Reduce file size without visible quality loss.",
    h1: "Compress Images Without Losing Quality",
    description: "Compress your images to 85% quality - the sweet spot where file size reduces significantly but quality remains excellent. Perfect balance for web and email.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["compress-image-for-web", "resize-image-for-web"],
  },
  {
    slug: "reduce-image-file-size",
    title: "Reduce Image File Size | Make Images Smaller",
    metaDescription: "Reduce image file sizes dramatically. Smaller files for faster uploads and downloads.",
    h1: "Reduce Image File Size",
    description: "Reduce image file sizes by resizing to reasonable dimensions (1920px max) and compressing to 75% quality. Perfect for email, web, and storage.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "combo",
    relatedPages: ["compress-image-for-email", "resize-image-for-web"],
  },
  {
    slug: "photo-resizer-for-email",
    title: "Photo Resizer for Email | Make Photos Email-Friendly",
    metaDescription: "Resize photos for email attachments. Reduce size to fit email limits.",
    h1: "Resize Photos for Email",
    description: "Resize photos to 800px width and compress to 75% quality - perfect for email attachments. Stay under email size limits while maintaining good quality.",
    settings: {
      width: 800,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "combo",
    relatedPages: ["resize-image-for-email", "compress-jpg-for-email"],
  },
  {
    slug: "website-image-optimizer",
    title: "Website Image Optimizer | Optimize Images for Fast Websites",
    metaDescription: "Optimize images for websites. Improve page speed and user experience.",
    h1: "Optimize Images for Websites",
    description: "Optimize website images by resizing to 1920px max and converting to WebP format. Reduce file sizes by 25-35% for faster loading websites.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/webp",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "convert-to-webp"],
  },
  {
    slug: "bulk-image-resizer",
    title: "Bulk Image Resizer | Resize Multiple Images Simultaneously",
    metaDescription: "Bulk resize images. Process multiple images with same settings at once.",
    h1: "Bulk Image Resizer",
    description: "Upload and resize multiple images at once with consistent settings. Perfect for processing photo albums, product catalogs, or bulk image optimization.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["batch-resize-images", "batch-resize-for-web"],
  },
  {
    slug: "high-quality-image-compressor",
    title: "High Quality Image Compressor | Compress Without Quality Loss",
    metaDescription: "Compress images while maintaining high quality. Reduce file size without degradation.",
    h1: "High Quality Image Compression",
    description: "Compress images using 90% quality setting - maintain excellent quality while reducing file size by 30-40%. Perfect when quality is critical.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "combo",
    relatedPages: ["compress-image-for-web", "compress-image-without-losing-quality"],
  },
  {
    slug: "convert-heic-to-jpg",
    title: "Convert HEIC to JPG | iPhone Photo Converter",
    metaDescription: "Convert HEIC images to JPG. Make iPhone photos compatible everywhere.",
    h1: "Convert HEIC to JPG",
    description: "Convert iPhone HEIC photos to JPG format for universal compatibility. Works on any device - upload your HEIC files and download as JPG.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "combo",
    relatedPages: ["convert-to-jpg", "resize-image-for-web"],
  },
  {
    slug: "fast-image-resizer",
    title: "Fast Image Resizer | Quick Image Resize Tool",
    metaDescription: "Fast image resizing. Resize images instantly in your browser.",
    h1: "Fast Image Resizer",
    description: "Lightning-fast image resizing - all processing happens in your browser. No uploads, no waiting. Resize images instantly.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "batch-resize-images"],
  },
  {
    slug: "professional-image-resizer",
    title: "Professional Image Resizer | High Quality Image Sizing",
    metaDescription: "Professional image resizing with quality preservation. For photographers and designers.",
    h1: "Professional Image Resizer",
    description: "Professional-grade image resizing with 95% quality preservation. Perfect for photographers, designers, and anyone who needs pristine image quality.",
    settings: {
      width: 0,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "combo",
    relatedPages: ["resize-image-for-print", "high-quality-image-compressor"],
  },
  {
    slug: "simple-image-resizer",
    title: "Simple Image Resizer | Easy to Use Image Resize Tool",
    metaDescription: "Simple, easy image resizing. No complicated settings - just upload and resize.",
    h1: "Simple Image Resizer",
    description: "The simplest way to resize images. No complicated settings - just upload your images and they're automatically optimized for web use.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "fast-image-resizer"],
  },
];

// Additional high-value pages for SEO
const additionalPages: ProgrammaticPage[] = [
  // Device-specific pages
  {
    slug: "resize-image-for-iphone",
    title: "Resize Images for iPhone | Optimize Photos for iOS",
    metaDescription: "Resize images for iPhone display and sharing. Perfect dimensions for iOS devices.",
    h1: "Resize Images for iPhone",
    description: "Optimize images for iPhone displays and sharing. Resize to 1125x2436 for iPhone X and newer, or customize for any iOS device.",
    settings: {
      width: 1125,
      height: 2436,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "device",
    relatedPages: ["resize-image-for-web", "convert-heic-to-jpg"],
  },
  {
    slug: "resize-image-for-android",
    title: "Resize Images for Android | Optimize Photos for Android Devices",
    metaDescription: "Resize images for Android phones and tablets. Perfect dimensions for Android displays.",
    h1: "Resize Images for Android",
    description: "Optimize images for Android devices. Resize to 1080x1920 for most Android phones or customize for your specific device.",
    settings: {
      width: 1080,
      height: 1920,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "device",
    relatedPages: ["resize-image-for-web", "resize-image-for-instagram-story"],
  },
  {
    slug: "resize-image-for-ipad",
    title: "Resize Images for iPad | iPad Display Optimization",
    metaDescription: "Resize images for iPad displays. Perfect for iPad wallpapers and content.",
    h1: "Resize Images for iPad",
    description: "Optimize images for iPad displays. Resize to 2048x2732 for iPad Pro or customize for any iPad model.",
    settings: {
      width: 2048,
      height: 2732,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "device",
    relatedPages: ["resize-image-for-iphone", "resize-to-2560x1440"],
  },
  
  // Industry-specific pages
  {
    slug: "resize-image-for-real-estate",
    title: "Resize Images for Real Estate | Property Photo Optimization",
    metaDescription: "Resize real estate photos for listings. Optimize property images for MLS and real estate websites.",
    h1: "Resize Images for Real Estate",
    description: "Optimize property photos for real estate listings. Resize to 1024x768 or 1200x800 for MLS compliance and fast loading on real estate websites.",
    settings: {
      width: 1200,
      height: 800,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "industry",
    relatedPages: ["resize-product-image", "resize-image-for-web"],
  },
  {
    slug: "resize-image-for-photography",
    title: "Resize Images for Photography Portfolio | Pro Photo Resizing",
    metaDescription: "Resize photos for photography portfolios. Maintain quality while optimizing for web galleries.",
    h1: "Resize Images for Photography Portfolios",
    description: "Resize photos for online portfolios while maintaining professional quality. Use 2400px width and 90% quality for stunning web galleries.",
    settings: {
      width: 2400,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "industry",
    relatedPages: ["professional-image-resizer", "resize-image-for-web"],
  },
  {
    slug: "resize-image-for-ecommerce",
    title: "Resize Images for E-commerce | Product Photo Optimization",
    metaDescription: "Resize product images for online stores. Optimize for Shopify, WooCommerce, and Amazon.",
    h1: "Resize Images for E-commerce",
    description: "Optimize product photos for e-commerce platforms. Resize to 1500x1500 for Amazon, Shopify, and most online stores. Fast loading with great detail.",
    settings: {
      width: 1500,
      height: 1500,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "industry",
    relatedPages: ["resize-product-image", "resize-image-for-web"],
  },
  {
    slug: "resize-image-for-shopify",
    title: "Resize Images for Shopify | Shopify Product Photo Size",
    metaDescription: "Resize images for Shopify stores. Perfect product image dimensions for Shopify.",
    h1: "Resize Images for Shopify",
    description: "Optimize product images for Shopify. Shopify recommends 2048x2048 for product photos. Resize to these dimensions for best results.",
    settings: {
      width: 2048,
      height: 2048,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "industry",
    relatedPages: ["resize-image-for-ecommerce", "resize-product-image"],
  },
  {
    slug: "resize-image-for-amazon",
    title: "Resize Images for Amazon | Amazon Product Image Size",
    metaDescription: "Resize images for Amazon listings. Meet Amazon's product image requirements.",
    h1: "Resize Images for Amazon",
    description: "Optimize product photos for Amazon. Amazon requires minimum 1000px on longest side, recommends 1500x1500 or larger for zoom functionality.",
    settings: {
      width: 1500,
      height: 1500,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "industry",
    relatedPages: ["resize-image-for-ecommerce", "resize-product-image"],
  },
  {
    slug: "resize-image-for-etsy",
    title: "Resize Images for Etsy | Etsy Product Photo Size",
    metaDescription: "Resize images for Etsy listings. Perfect dimensions for Etsy product photos.",
    h1: "Resize Images for Etsy",
    description: "Optimize product photos for Etsy. Etsy displays images at 2000x2000 maximum. Resize to these dimensions for beautiful product listings.",
    settings: {
      width: 2000,
      height: 2000,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "industry",
    relatedPages: ["resize-image-for-ecommerce", "resize-product-image"],
  },
  
  // Specific document/ID pages
  {
    slug: "resize-passport-photo",
    title: "Resize Passport Photo | Passport Photo Size Requirements",
    metaDescription: "Resize photos for passport applications. Meet official passport photo size requirements.",
    h1: "Resize Passport Photos",
    description: "Resize photos to meet passport requirements. Standard passport photo is 2x2 inches (600x600 pixels at 300 DPI). Perfect for passport applications.",
    settings: {
      width: 600,
      height: 600,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "document",
    relatedPages: ["resize-profile-picture", "resize-to-500x500"],
  },
  {
    slug: "resize-resume-photo",
    title: "Resize Resume Photo | Professional Headshot Resizing",
    metaDescription: "Resize photos for resumes and CVs. Professional headshot dimensions.",
    h1: "Resize Photos for Resumes",
    description: "Resize headshots for resumes and CVs. Use 400x400 or 500x500 for professional resume photos that look sharp when printed or viewed digitally.",
    settings: {
      width: 500,
      height: 500,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "document",
    relatedPages: ["resize-profile-picture", "resize-image-for-linkedin-profile"],
  },
  {
    slug: "resize-id-photo",
    title: "Resize ID Photo | ID Card Photo Requirements",
    metaDescription: "Resize photos for ID cards and badges. Meet standard ID photo requirements.",
    h1: "Resize ID Photos",
    description: "Resize photos for ID cards, badges, and identification documents. Standard size is 400x600 pixels for most ID requirements.",
    settings: {
      width: 400,
      height: 600,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "document",
    relatedPages: ["resize-passport-photo", "resize-resume-photo"],
  },
  
  // Wallpaper and background pages
  {
    slug: "resize-desktop-wallpaper",
    title: "Resize Desktop Wallpaper | HD Wallpaper Resizing",
    metaDescription: "Resize images for desktop wallpapers. Perfect HD and 4K wallpaper dimensions.",
    h1: "Resize Desktop Wallpapers",
    description: "Resize images for desktop wallpapers. Use 1920x1080 for Full HD, 2560x1440 for 2K, or 3840x2160 for 4K displays.",
    settings: {
      width: 1920,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "wallpaper",
    relatedPages: ["resize-to-1920x1080", "resize-to-3840x2160"],
  },
  {
    slug: "resize-phone-wallpaper",
    title: "Resize Phone Wallpaper | Mobile Wallpaper Size",
    metaDescription: "Resize images for phone wallpapers. Perfect mobile and iPhone wallpaper dimensions.",
    h1: "Resize Phone Wallpapers",
    description: "Resize images for mobile wallpapers. Use 1080x1920 for most phones or 1125x2436 for iPhone X and newer models.",
    settings: {
      width: 1080,
      height: 1920,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "wallpaper",
    relatedPages: ["resize-image-for-iphone", "resize-to-1080x1920"],
  },
  {
    slug: "resize-zoom-background",
    title: "Resize Zoom Background | Virtual Background Size",
    metaDescription: "Resize images for Zoom virtual backgrounds. Perfect Zoom background dimensions.",
    h1: "Resize Zoom Virtual Backgrounds",
    description: "Optimize images for Zoom virtual backgrounds. Zoom recommends 1920x1080 (16:9 ratio) for best results.",
    settings: {
      width: 1920,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "wallpaper",
    relatedPages: ["resize-desktop-wallpaper", "resize-to-1920x1080"],
  },
  {
    slug: "resize-teams-background",
    title: "Resize Microsoft Teams Background | Teams Virtual Background",
    metaDescription: "Resize images for Microsoft Teams backgrounds. Perfect Teams background size.",
    h1: "Resize Microsoft Teams Backgrounds",
    description: "Optimize images for Microsoft Teams virtual backgrounds. Teams works best with 1920x1080 images for clear, professional backgrounds.",
    settings: {
      width: 1920,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "wallpaper",
    relatedPages: ["resize-zoom-background", "resize-to-1920x1080"],
  },
  
  // More social media specific variants
  {
    slug: "resize-twitter-card",
    title: "Resize Twitter Card Image | Twitter Summary Card Size",
    metaDescription: "Resize images for Twitter cards. Perfect Twitter summary card dimensions.",
    h1: "Resize Twitter Card Images",
    description: "Optimize images for Twitter cards. Twitter summary cards display best at 1200x628 pixels for maximum engagement.",
    settings: {
      width: 1200,
      height: 628,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-twitter-post", "resize-to-1200x630"],
  },
  {
    slug: "resize-linkedin-post-image",
    title: "Resize LinkedIn Post Image | LinkedIn Image Size",
    metaDescription: "Resize images for LinkedIn posts. Optimal LinkedIn post image dimensions.",
    h1: "Resize Images for LinkedIn Posts",
    description: "Optimize images for LinkedIn engagement. LinkedIn displays post images best at 1200x627 pixels.",
    settings: {
      width: 1200,
      height: 627,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-linkedin-post", "resize-to-1200x630"],
  },
  {
    slug: "resize-facebook-cover-photo",
    title: "Resize Facebook Cover Photo | FB Cover Size 2024",
    metaDescription: "Resize Facebook cover photos to perfect size. Current Facebook cover dimensions.",
    h1: "Resize Facebook Cover Photos",
    description: "Create perfect Facebook cover photos. Facebook covers display at 820x312 pixels on desktop and scale for mobile.",
    settings: {
      width: 820,
      height: 312,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-facebook-cover", "resize-image-for-facebook-post"],
  },
  {
    slug: "resize-youtube-channel-art",
    title: "Resize YouTube Channel Art | YouTube Banner Size",
    metaDescription: "Resize YouTube channel banners. Perfect YouTube channel art dimensions.",
    h1: "Resize YouTube Channel Art",
    description: "Create perfect YouTube channel banners. YouTube channel art displays at 2560x1440 for optimal viewing across all devices.",
    settings: {
      width: 2560,
      height: 1440,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "social-media",
    relatedPages: ["resize-image-for-youtube-banner", "resize-to-2560x1440"],
  },
  {
    slug: "resize-instagram-profile-picture",
    title: "Resize Instagram Profile Picture | IG Profile Photo Size",
    metaDescription: "Resize Instagram profile pictures. Perfect Instagram profile photo dimensions.",
    h1: "Resize Instagram Profile Pictures",
    description: "Create perfect Instagram profile pictures. Instagram displays profile photos at 320x320 pixels but upload at 180x180 minimum.",
    settings: {
      width: 320,
      height: 320,
      outputFormat: "image/jpeg",
      quality: 90,
    },
    category: "social-media",
    relatedPages: ["resize-profile-picture", "resize-image-for-instagram-post"],
  },
  
  // Print-specific pages
  {
    slug: "resize-image-for-4x6-print",
    title: "Resize Image for 4x6 Print | 4x6 Photo Size",
    metaDescription: "Resize images for 4x6 inch prints. Perfect dimensions for standard photo prints.",
    h1: "Resize Images for 4x6 Prints",
    description: "Optimize images for 4x6 inch prints. Use 1800x1200 pixels (300 DPI) for high-quality 4x6 photo prints.",
    settings: {
      width: 1800,
      height: 1200,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "print",
    relatedPages: ["resize-image-for-print", "resize-image-for-8x10-print"],
  },
  {
    slug: "resize-image-for-5x7-print",
    title: "Resize Image for 5x7 Print | 5x7 Photo Size",
    metaDescription: "Resize images for 5x7 inch prints. Perfect 5x7 photo dimensions.",
    h1: "Resize Images for 5x7 Prints",
    description: "Optimize images for 5x7 inch prints. Use 2100x1500 pixels (300 DPI) for professional-quality 5x7 prints.",
    settings: {
      width: 2100,
      height: 1500,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "print",
    relatedPages: ["resize-image-for-4x6-print", "resize-image-for-8x10-print"],
  },
  {
    slug: "resize-image-for-8x10-print",
    title: "Resize Image for 8x10 Print | 8x10 Photo Size",
    metaDescription: "Resize images for 8x10 inch prints. Perfect 8x10 photo print dimensions.",
    h1: "Resize Images for 8x10 Prints",
    description: "Optimize images for 8x10 inch prints. Use 3000x2400 pixels (300 DPI) for high-quality 8x10 photo prints.",
    settings: {
      width: 3000,
      height: 2400,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "print",
    relatedPages: ["resize-image-for-5x7-print", "resize-image-for-print"],
  },
  {
    slug: "resize-image-for-11x14-print",
    title: "Resize Image for 11x14 Print | 11x14 Photo Size",
    metaDescription: "Resize images for 11x14 inch prints. Large format photo dimensions.",
    h1: "Resize Images for 11x14 Prints",
    description: "Optimize images for 11x14 inch prints. Use 4200x3300 pixels (300 DPI) for professional large-format prints.",
    settings: {
      width: 4200,
      height: 3300,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "print",
    relatedPages: ["resize-image-for-8x10-print", "resize-image-for-print"],
  },
  {
    slug: "resize-image-for-poster",
    title: "Resize Image for Poster | Large Poster Print Size",
    metaDescription: "Resize images for poster printing. Optimize for large format posters.",
    h1: "Resize Images for Posters",
    description: "Optimize images for poster printing. Use 5400x3600 pixels for 18x24 inch posters at 300 DPI, or scale proportionally for larger sizes.",
    settings: {
      width: 5400,
      height: 3600,
      outputFormat: "image/jpeg",
      quality: 95,
    },
    category: "print",
    relatedPages: ["resize-image-for-11x14-print", "resize-image-for-print"],
  },
  
  // More specific combo pages
  {
    slug: "reduce-jpg-file-size",
    title: "Reduce JPG File Size | Make JPEG Smaller",
    metaDescription: "Reduce JPG file sizes dramatically. Compress JPEG images for email and web.",
    h1: "Reduce JPG File Size",
    description: "Reduce JPG file sizes by adjusting quality and dimensions. Compress to 75% quality and resize to 1920px max for perfect balance of size and quality.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "combo",
    relatedPages: ["compress-image-for-web", "reduce-image-file-size"],
  },
  {
    slug: "reduce-png-file-size",
    title: "Reduce PNG File Size | Make PNG Smaller",
    metaDescription: "Reduce PNG file sizes. Convert to JPG or resize for smaller PNG files.",
    h1: "Reduce PNG File Size",
    description: "Reduce PNG file sizes by converting to JPG (for photos) or resizing dimensions. PNG works best for logos and graphics, JPG for photos.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["convert-png-to-jpg", "compress-png-to-jpg"],
  },
  {
    slug: "shrink-image",
    title: "Shrink Image | Make Images Smaller",
    metaDescription: "Shrink images to reduce file size. Make images smaller for faster loading.",
    h1: "Shrink Images",
    description: "Shrink images by reducing dimensions and quality. Reduce to 50% size or customize dimensions to make images dramatically smaller.",
    settings: {
      width: 0,
      height: 0,
      usePercentage: true,
      percentage: 50,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "combo",
    relatedPages: ["reduce-image-file-size", "resize-image-percentage"],
  },
  {
    slug: "downscale-image",
    title: "Downscale Image | Reduce Image Resolution",
    metaDescription: "Downscale images to lower resolution. Reduce image size and quality.",
    h1: "Downscale Images",
    description: "Downscale high-resolution images to web-friendly sizes. Reduce from 4K or higher to 1920px for fast loading without visible quality loss.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["reduce-image-file-size", "resize-image-for-web"],
  },
  {
    slug: "crop-and-resize-image",
    title: "Crop and Resize Image | Image Cropping and Resizing",
    metaDescription: "Crop and resize images. Adjust dimensions and crop to perfect size.",
    h1: "Crop and Resize Images",
    description: "Resize images to specific dimensions - our tool automatically crops/scales to fit your target size while maintaining the best composition.",
    settings: {
      width: 1920,
      height: 1080,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "square-image-maker"],
  },
  {
    slug: "make-image-smaller",
    title: "Make Image Smaller | Reduce Image Size Online",
    metaDescription: "Make images smaller for web and email. Reduce image file sizes online free.",
    h1: "Make Images Smaller",
    description: "Make images smaller by resizing to 1920px max width and compressing to 75% quality. Perfect for email attachments and faster website loading.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "combo",
    relatedPages: ["reduce-image-file-size", "shrink-image"],
  },
  {
    slug: "scale-image",
    title: "Scale Image | Resize and Scale Images Proportionally",
    metaDescription: "Scale images proportionally. Resize while maintaining aspect ratio.",
    h1: "Scale Images Proportionally",
    description: "Scale images up or down while maintaining aspect ratio. Enter desired width or height and the other dimension adjusts automatically.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-image-percentage", "resize-image-for-web"],
  },
  {
    slug: "enlarge-image",
    title: "Enlarge Image | Upscale Image Size",
    metaDescription: "Enlarge images to larger dimensions. Upscale photos to higher resolution.",
    h1: "Enlarge Images",
    description: "Enlarge images to larger dimensions. Note: enlarging beyond original size may reduce quality. Use 100% quality for best results when upscaling.",
    settings: {
      width: 3840,
      height: 2160,
      outputFormat: "image/jpeg",
      quality: 100,
    },
    category: "combo",
    relatedPages: ["resize-to-3840x2160", "resize-4k-3840x2160"],
  },
  {
    slug: "image-size-reducer",
    title: "Image Size Reducer | Reduce Photo File Size",
    metaDescription: "Reduce image file sizes online. Free image size reducer tool.",
    h1: "Image Size Reducer",
    description: "Reduce image file sizes by up to 70% while maintaining good quality. Perfect for email, web, and storage optimization.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 75,
    },
    category: "combo",
    relatedPages: ["reduce-image-file-size", "compress-image-for-web"],
  },
  {
    slug: "photo-optimizer",
    title: "Photo Optimizer | Optimize Photos for Web",
    metaDescription: "Optimize photos for web and email. Reduce file size while maintaining quality.",
    h1: "Photo Optimizer",
    description: "Optimize photos for web use by resizing to 1920px and compressing to 80% quality. Perfect balance of quality and file size.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 80,
    },
    category: "combo",
    relatedPages: ["resize-image-for-web", "compress-image-for-web"],
  },
  {
    slug: "picture-resizer",
    title: "Picture Resizer | Resize Pictures Online Free",
    metaDescription: "Resize pictures online for free. Fast picture resizing tool.",
    h1: "Picture Resizer",
    description: "Resize pictures to any dimension. Upload your photos and resize to custom dimensions or use presets for common sizes.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["photo-optimizer", "resize-image-for-web"],
  },
  {
    slug: "free-image-resizer",
    title: "Free Image Resizer | Resize Images Online Free",
    metaDescription: "Free image resizer - no sign up required. Resize unlimited images for free.",
    h1: "Free Image Resizer",
    description: "Free image resizing tool - no sign up, no watermarks, no limits. Resize as many images as you need, completely free.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["fast-image-resizer", "simple-image-resizer"],
  },
  {
    slug: "online-image-resizer",
    title: "Online Image Resizer | Resize Images in Browser",
    metaDescription: "Online image resizer - resize images directly in your browser. No uploads needed.",
    h1: "Online Image Resizer",
    description: "Resize images online directly in your browser. All processing happens locally - your images never leave your device. Fast, secure, and private.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["free-image-resizer", "fast-image-resizer"],
  },
  {
    slug: "jpeg-resizer",
    title: "JPEG Resizer | Resize JPEG Images Online",
    metaDescription: "Resize JPEG images online. Fast JPEG resizing and compression.",
    h1: "JPEG Resizer",
    description: "Resize JPEG images to any dimension while maintaining quality. Compress and optimize JPEGs for web and email.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/jpeg",
      quality: 85,
    },
    category: "combo",
    relatedPages: ["resize-jpg-for-web", "compress-jpg-for-email"],
  },
  {
    slug: "png-resizer",
    title: "PNG Resizer | Resize PNG Images Online",
    metaDescription: "Resize PNG images while maintaining transparency. Free PNG resizer tool.",
    h1: "PNG Resizer",
    description: "Resize PNG images while preserving transparency. Perfect for logos, graphics, and images requiring transparent backgrounds.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/png",
      quality: 100,
    },
    category: "combo",
    relatedPages: ["resize-png-for-web", "convert-png-to-jpg"],
  },
  {
    slug: "gif-resizer",
    title: "GIF Resizer | Resize GIF Images",
    metaDescription: "Resize GIF images. Reduce GIF file size while maintaining quality.",
    h1: "GIF Resizer",
    description: "Resize GIF images to reduce file size. Note: This converts static GIF to JPG or PNG - animation will be lost.",
    settings: {
      width: 1920,
      height: 0,
      outputFormat: "image/png",
      quality: 100,
    },
    category: "combo",
    relatedPages: ["convert-gif-to-jpg", "convert-gif-to-png"],
  },
];

export const allProgrammaticPages = [
  ...socialMediaPages,
  ...useCasePages,
  ...formatConversionPages,
  ...dimensionPages,
  ...comboPages,
  ...additionalPages,
];

export function getProgrammaticPage(slug: string): ProgrammaticPage | null {
  return allProgrammaticPages.find(page => page.slug === slug) || null;
}

export function getAllProgrammaticSlugs(): string[] {
  return allProgrammaticPages.map(page => page.slug);
}

